# Generated by Django 4.1.7 on 2023-02-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('band', models.CharField(max_length=30)),
                ('song_title', models.CharField(max_length=30)),
                ('song_url', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
    ]
