# Generated by Django 4.1.7 on 2023-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_player', '0002_rename_songs_song_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
