# Generated by Django 4.1.6 on 2023-02-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_player', '0003_alter_song_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_url',
            field=models.CharField(max_length=15),
        ),
    ]
