# Generated by Django 4.1.6 on 2023-02-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_player', '0004_alter_song_song_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='dedescription_p',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
